In [ ]:
- pandas : Used for Data base reading writing Modify the data

- numpy : Used for Numerical or math operations

- matplotlib : Used for plotting

- seaborn : Used for plotting

In [ ]:
==============================EDA===================================
1) pandas                    :   Data frame operations
2) numpy                     :   math operations
3) matplotlib                :   plotting or graphs
4) seaborn                   :   plotting or graphs
5) plotly                    :   plotting or graphs
6) bokhe                     :   plotting or graphs

====================== Machine learning ==========================
7) sickit-learn(sklean)      :   For ALL ML algorithms 
8) stats                     :   some statistical operations 

====================== Deep learning ================================
9) Tensorflow                :   Deep learning models (Google)
10) keras                    :   Deep learning models tensorflow as backend
11) pytorch                  :   Deep learning models (Meta)
12) opencv                   :   Image and Video opeartions
13) pillow                   :   Image operations

=================== Object Detection models(Transfer learning)========================
14) Mobilenet                :   Deep learning packages
15) VGGnet                   :   Deep learning packages
16) Resnet                   :   Deep learning packages
17) Inceptionv3              :   Deep learning packages
18) YOLO                     :   Deep learning packages

====================== Natural Language process ===============================
19) NLTK                     :   Natural Langauge Tool Kit
20) SpCy                     :   Alternative to NLTK
21) Wordcloud                :   Text representation

======================= NLP word Embedding Models ==============================
22) Word2Vec                 :   Google
23) GloVe                    :   Stanford
24) Fasttext                 :   Meta(Face book)

====================== ALLEN NLP (organization) ===========================
25) NLP applications         :  Pyspark as Backend

======================= Optical Character Recognition(OCR) ===============
Extract the text from the image
26) Tesseract
27) easyocr

=========================BERT=======================================
BERT: Bi directional Encoded Representations from Transformers
28) Transformers          : Hugging face (Google)

==================== WebScrapping ===========================
29) SQLITE                 : Connect the Database using python
30) Selenium
31) Beautiful soup
32) Regex

===================== GenAI and LLM =============================
33) Langchain             :  To Connect all  LLM models
34) GPT                   :  OpenAI
35) Gemini                :  Google
36) Llama                 :  Meta
37) Grok                  :  XAi
38) BedRock               :  Amazon
39) Claude AI             :  Anthropic

=================== Agentic AI==================================
40) Langraph
41) CrewAI
42) Phidata
43) Autogen
==================== API creation==============================
44) Flask
45) FastAPI
46) Gradio
47) Django 

===================== WebAppliaction ===========================
48) Streamlit

======================= Model deployment(MLops) ==============================
49) mlflow
50) Kubeflow

========================== Cloud AI =========================================
51) Azure Cognitive services
52) Azure ML Studio
53) GCP vertexAI
54) AWS Sagemaker

=============================== Extra ========================================
55) random
56) time
57) math
58) logging
59) warnings
60) date

**Step-1: Import packages**

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

**Step-2: Create Dataframe using List**

In [8]:
names=['Ramesh','Suresh','Sathish']
# pd.DataFrame(data,index,columns)
pd.DataFrame(names)

         0
0   Ramesh
1   Suresh
2  Sathish

**Step-3: Add column**

In [15]:
names=['Ramesh','Suresh','Sathish']
# pd.DataFrame(data,index,columns)
pd.DataFrame(names,columns=['Names'])

     Names
0   Ramesh
1   Suresh
2  Sathish

**Step-4:update the index**

In [20]:
names=['Ramesh','Suresh','Sathish']
# pd.DataFrame(data,index,columns)
pd.DataFrame(names,
             index=['A','B','C'])

         0
A   Ramesh
B   Suresh
C  Sathish

In [22]:
names=['Ramesh','Suresh','Sathish']
cols=['Names']
idx=['A','B','C']
pd.DataFrame(names,
             index=idx,
             columns=cols)

     Names
A   Ramesh
B   Suresh
C  Sathish

**Step-5: Create a DataFrame with Multiple columns**

In [39]:
names=['Ramesh','Suresh','Sathish']
city=['Hyd','Mumbai','Blr']
data=[names,city]

cols=['Names','City']
idx=['A','B','C']
pd.DataFrame(data,index=cols,columns=idx).T

     Names    City
A   Ramesh     Hyd
B   Suresh  Mumbai
C  Sathish     Blr

In [43]:
names=['Ramesh','Suresh','Sathish']
city=['Hyd','Mumbai','Blr']
data=zip(names,city)

cols=['Names','City']
idx=['A','B','C']
pd.DataFrame(data,index=idx,columns=cols)

     Names    City
A   Ramesh     Hyd
B   Suresh  Mumbai
C  Sathish     Blr

In [45]:
names=['Ramesh','Suresh','Sathish']
city=['Hyd','Mumbai','Blr']
age=[20,22,24]
data=zip(names,city,age)

cols=['Names','City','Age']
idx=['A','B','C']
pd.DataFrame(data,index=idx,columns=cols)

     Names    City  Age
A   Ramesh     Hyd   20
B   Suresh  Mumbai   22
C  Sathish     Blr   24

**Step-6: How to add data to empty dataframe**

In [58]:
l=[]
l.append(20)
l

d={}
d['Names']=['Ramesh','Suresh','Sathish']
print(d)

s=''
s=s+'apple'
s

{'Names': ['Ramesh', 'Suresh', 'Sathish']}

'apple'

In [64]:
df=pd.DataFrame()
df['Names']=['Ramesh','Suresh','Sathish']
df['Age']=[20,22,24]
df['City']=['Hyd','Mumbai','Blr']
df

     Names  Age    City
0   Ramesh   20     Hyd
1   Suresh   22  Mumbai
2  Sathish   24     Blr

**Step-7: Create a dataframe using dictionary**

In [73]:
d={'Names':['Ramesh','Suresh','Sathish'],
  'Age':[20,22,24],
  'City':['Hyd','Mumbai','Blr']}
df=pd.DataFrame(d)
df

     Names  Age    City
0   Ramesh   20     Hyd
1   Suresh   22  Mumbai
2  Sathish   24     Blr

**Step-8 Methods**

- shape

- size

- columns

- dtypes

- isnull

In [76]:
df.shape

(3, 3)

In [78]:
df.size

9

In [80]:
df.columns

Index(['Names', 'Age', 'City'], dtype='object')

In [82]:
df.dtypes

Names    object
Age       int64
City     object
dtype: object

In [86]:
df.isnull()

   Names    Age   City
0  False  False  False
1  False  False  False
2  False  False  False

In [90]:
# column wise null values
df.isnull().sum()

Names    0
Age      0
City     0
dtype: int64

**Step-9: Rename the columns**

In [92]:
d={'Names':['Ramesh','Suresh','Sathish'],
  'Age':[20,22,24],
  'City':['Hyd','Mumbai','Blr']}
df=pd.DataFrame(d)
df

     Names  Age    City
0   Ramesh   20     Hyd
1   Suresh   22  Mumbai
2  Sathish   24     Blr

In [97]:
# If we want to rename all the columns
df.columns=['A','B','C']
df

         A   B       C
0   Ramesh  20     Hyd
1   Suresh  22  Mumbai
2  Sathish  24     Blr

In [101]:
df.index=['A','B','C']
df

         A   B       C
A   Ramesh  20     Hyd
B   Suresh  22  Mumbai
C  Sathish  24     Blr

In [103]:
d={'Names':['Ramesh','Suresh','Sathish'],
  'Age':[20,22,24],
  'City':['Hyd','Mumbai','Blr']}
df=pd.DataFrame(d)
df

     Names  Age    City
0   Ramesh   20     Hyd
1   Suresh   22  Mumbai
2  Sathish   24     Blr

In [111]:
#df.rename(mapper,index,columns,axis,inplace)
d={'Names':'A', 'Age':'B','City':'C'}
df.rename(columns=d,inplace=True)

In [113]:
df

         A   B       C
0   Ramesh  20     Hyd
1   Suresh  22  Mumbai
2  Sathish  24     Blr

In [ ]:
# I want to change my columns
# I provided dictionary of a mapper with new columns

# I want to feed a food you
# I prepared a food

In [115]:
d={'Names':['Ramesh','Suresh','Sathish'],
  'Age':[20,22,24],
  'City':['Hyd','Mumbai','Blr']}
df=pd.DataFrame(d)
#df.rename(mapper,index,columns,axis,inplace)
d={'Names':'A', 'Age':'B','City':'C'}
df.rename(index=d,inplace=True)
df

     Names  Age    City
0   Ramesh   20     Hyd
1   Suresh   22  Mumbai
2  Sathish   24     Blr

In [117]:
#df.rename(mapper,index,columns,axis,inplace)
d={'Names':['Ramesh','Suresh','Sathish'],
  'Age':[20,22,24],
  'City':['Hyd','Mumbai','Blr']}
df=pd.DataFrame(d)
#df.rename(mapper,index,columns,axis,inplace)
d={0:'A', 1:'B',2:'C'}
df.rename(index=d,inplace=True)
df

     Names  Age    City
A   Ramesh   20     Hyd
B   Suresh   22  Mumbai
C  Sathish   24     Blr

In [ ]:
#df.rename(mapper,index,columns,axis,inplace)
d={0:'A', 1:'B',2:'C'}
df.rename(index=d,inplace=True)
d={'Names':'A', 'Age':'B','City':'C'}
df.rename(columns=d,inplace=True)
d={'Names':'A', 'Age':'B','City':'C'}


df.rename(d,inplace=True) # my python not unde
# this mapper belongs to index or column
d={'Names':'A', 'Age':'B','City':'C'}
df.rename(columns=d,inplace=True)

d={0:'A', 1:'B',2:'C'}
df.rename(index=d,inplace=True)

In [123]:
d={'Names':['Ramesh','Suresh','Sathish'],
  'Age':[20,22,24],
  'City':['Hyd','Mumbai','Blr']}
df=pd.DataFrame(d)
df
d={'Names':'A', 'Age':'B','City':'C'}
df.rename(d,inplace=True)
df.rename(d,
          axis=1,
          inplace=True)
df
# this guy used mapper
# also he told me that it is a column mapper axis=1

         A   B       C
0   Ramesh  20     Hyd
1   Suresh  22  Mumbai
2  Sathish  24     Blr

**Step-10:How to add a new data to existed dataframe**

In [8]:
import pandas as pd
d={'Names':['Ramesh','Suresh','Sathish'],
  'Age':[20,22,24],
  'City':['Hyd','Mumbai','Blr']}
df=pd.DataFrame(d)
df['Marks']=[100,200,300] # adding a new column
df['Age']=[100,200,300]   # modify the exist column
df

     Names  Age    City  Marks
0   Ramesh  100     Hyd    100
1   Suresh  200  Mumbai    200
2  Sathish  300     Blr    300

**Step-11: Save the dataframe**

- if we want to read or write we need 3 values

  - where you want to save
 
  - on which name you want to save
 
  - on which format you waant to save 
 
- filename.txt

- filename.csv  of filename.xlsx

- if I provide only file name it will save at cwd

In [11]:
df

     Names  Age    City  Marks
0   Ramesh  100     Hyd    100
1   Suresh  200  Mumbai    200
2  Sathish  300     Blr    300

In [21]:
df.to_csv('data.csv',index=False)

df.to_csv(r'C:\Users\omkar\OneDrive\Documents\Data science\data.csv')

**Step-12:Read the dataframe**

In [23]:
pd.read_csv('data.csv')

     Names  Age    City  Marks
0   Ramesh  100     Hyd    100
1   Suresh  200  Mumbai    200
2  Sathish  300     Blr    300

In [25]:
df.to_excel('data.xlsx',index=False)

In [27]:
pd.read_excel('data.xlsx')

     Names  Age    City  Marks
0   Ramesh  100     Hyd    100
1   Suresh  200  Mumbai    200
2  Sathish  300     Blr    300