In [ ]:
############### EDA ###########################
1. Data preprocess
    - missing value analysis
    - data types mismatch
2. Data analysis
    - Categorical
    - Numerical
    - Bi variate
    - Multivariate
    - Outlier analysis
3. Feature engineeing 
    - Impute the outliers
    - ML needs number Eng to Numbers : Encoding
    - Scaling : Standardization and Normalization
    - Transforamtion : Convert into Normal distribution

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


visa_df=pd.read_csv(r"C:\Users\omkar\OneDrive\Documents\Gen_AI\Data_files\Visadataset.csv")

cat=visa_df.select_dtypes(include='object').columns
num=visa_df.select_dtypes(exclude='object').columns

In [3]:
cat

Index(['case_id', 'continent', 'education_of_employee', 'has_job_experience',
       'requires_job_training', 'region_of_employment', 'unit_of_wage',
       'full_time_position', 'case_status'],
      dtype='object')

**case_status**

In [6]:
# step-1: find how many unique lables are there
visa_df['case_status'].unique()

array(['Denied', 'Certified'], dtype=object)

In [8]:
# step-2: Create a dictionary by assign a values to the lables
#         follow the alpahabetical order
#         python index start with zero
d={'Certified':0,'Denied':1}
d           # think how create a dictionary automatically

{'Certified': 0, 'Denied': 1}

In [14]:
# step-3: map these dictionary to original value
visa_df['case_status']=visa_df['case_status'].map(d)

In [16]:
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,1
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,0
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,1
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,1
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,0
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,0
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,0
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,0
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,0
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,0

In [18]:
# Read the data again
visa_df=pd.read_csv(r"C:\Users\omkar\OneDrive\Documents\Gen_AI\Data_files\Visadataset.csv")
visa_df['case_status'].unique()
d={'Certified':0,'Denied':1}
visa_df['case_status']=visa_df['case_status'].map(d)

In [20]:
visa_df=pd.read_csv(r"C:\Users\omkar\OneDrive\Documents\Gen_AI\Data_files\Visadataset.csv")
visa_df['continent'].unique()
d={'Asia':0,'Africa':1}

array(['Asia', 'Africa', 'North America', 'Europe', 'South America',
       'Oceania'], dtype=object)

In [36]:
labels=visa_df['continent'].unique()
d={}
for i in range(len(labels)):
    d[labels[i]]=i
d

{'Asia': 0,
 'Africa': 1,
 'North America': 2,
 'Europe': 3,
 'South America': 4,
 'Oceania': 5}

In [40]:
#{<key>:<value> for i in rane}
labels=sorted(visa_df['continent'].unique())
d={labels[i]:i for i in range(len(labels))}
d

{'Africa': 0,
 'Asia': 1,
 'Europe': 2,
 'North America': 3,
 'Oceania': 4,
 'South America': 5}

In [42]:
visa_df=pd.read_csv(r"C:\Users\omkar\OneDrive\Documents\Gen_AI\Data_files\Visadataset.csv")
labels=sorted(visa_df['continent'].unique())
d={labels[i]:i for i in range(len(labels))}
visa_df['continent']=visa_df['continent'].map(d)

In [44]:
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,1,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,1,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,1,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,1,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,0,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,1,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,Certified
25476,EZYV25477,1,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,Certified
25477,EZYV25478,1,Master's,Y,N,1121,1910,South,146298.8500,Year,N,Certified
25478,EZYV25479,1,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,Certified
25479,EZYV25480,1,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,Certified

In [46]:
visa_df=pd.read_csv(r"C:\Users\omkar\OneDrive\Documents\Gen_AI\Data_files\Visadataset.csv")
for i in cat[1:]:
    labels=sorted(visa_df[i].unique())
    d={labels[i]:i for i in range(len(labels))}
    visa_df[i]=visa_df[i].map(d)

In [48]:
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,1,2,0,0,14513,2007,4,592.2029,0,1,1
1,EZYV02,1,3,1,0,2412,2002,2,83425.6500,3,1,0
2,EZYV03,1,0,0,1,44444,2008,4,122996.8600,3,1,1
3,EZYV04,1,0,0,0,98,1897,4,83434.0300,3,1,1
4,EZYV05,0,3,1,0,1082,2005,3,149907.3900,3,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,1,0,1,1,2601,2008,3,77092.5700,3,1,0
25476,EZYV25477,1,2,1,0,3274,2006,2,279174.7900,3,1,0
25477,EZYV25478,1,3,1,0,1121,1910,3,146298.8500,3,0,0
25478,EZYV25479,1,3,1,1,1918,1887,4,86154.7700,3,1,0
25479,EZYV25480,1,0,1,0,3195,1960,1,70876.9100,3,1,0

- sklearn aka scikit-learn

    - preprocessing

        - LableEncoder

- Step1: Import the module

- Step2: Save the module

- Step3: apply fit_transform

    - fit means create a dictionary
 
    - transform means apply dictionary so that data will be transformed

In [54]:
# Read the data again
visa_df=pd.read_csv(r"C:\Users\omkar\OneDrive\Documents\Gen_AI\Data_files\Visadataset.csv")

In [61]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
visa_df['case_status']=le.fit_transform(visa_df['case_status'])
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,1
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,0
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,1
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,1
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,0
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,0
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,0
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,0
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,0
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,0

In [63]:
visa_df['continent']=le.fit_transform(visa_df['continent'])
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,1,High School,N,N,14513,2007,West,592.2029,Hour,Y,1
1,EZYV02,1,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,0
2,EZYV03,1,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,1
3,EZYV04,1,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,1
4,EZYV05,0,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,0
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,1,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,0
25476,EZYV25477,1,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,0
25477,EZYV25478,1,Master's,Y,N,1121,1910,South,146298.8500,Year,N,0
25478,EZYV25479,1,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,0
25479,EZYV25480,1,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,0

In [67]:
le.inverse_transform(visa_df['continent'])[:5]

array(['Asia', 'Asia', 'Asia', 'Asia', 'Africa'], dtype=object)

In [69]:
visa_df=pd.read_csv(r"C:\Users\omkar\OneDrive\Documents\Gen_AI\Data_files\Visadataset.csv")
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
for i in cat[1:]:
    visa_df[i]=le.fit_transform(visa_df[i])
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,1,2,0,0,14513,2007,4,592.2029,0,1,1
1,EZYV02,1,3,1,0,2412,2002,2,83425.6500,3,1,0
2,EZYV03,1,0,0,1,44444,2008,4,122996.8600,3,1,1
3,EZYV04,1,0,0,0,98,1897,4,83434.0300,3,1,1
4,EZYV05,0,3,1,0,1082,2005,3,149907.3900,3,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,1,0,1,1,2601,2008,3,77092.5700,3,1,0
25476,EZYV25477,1,2,1,0,3274,2006,2,279174.7900,3,1,0
25477,EZYV25478,1,3,1,0,1121,1910,3,146298.8500,3,0,0
25478,EZYV25479,1,3,1,1,1918,1887,4,86154.7700,3,1,0
25479,EZYV25480,1,0,1,0,3195,1960,1,70876.9100,3,1,0

**OneHotEncoder**

- OneHot means at a time one will be ON(1) another wil be OFF(0)

|case_status|case_status_Denied|case_status_Certified|
|-|-|-|
|Denied|1|0|
|Certified|0|1|
|Certified|0|1|
|Denied|1|0|

In [98]:
visa_df=pd.read_csv(r"C:\Users\omkar\OneDrive\Documents\Gen_AI\Data_files\Visadataset.csv")
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,Certified
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,Certified
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,Certified
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,Certified
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,Certified

In [100]:
pd.get_dummies(visa_df,
               columns=cat[1:],
               dtype=int)

,case_id,no_of_employees,yr_of_estab,prevailing_wage,continent_Africa,continent_Asia,continent_Europe,continent_North America,continent_Oceania,continent_South America,...,region_of_employment_South,region_of_employment_West,unit_of_wage_Hour,unit_of_wage_Month,unit_of_wage_Week,unit_of_wage_Year,full_time_position_N,full_time_position_Y,case_status_Certified,case_status_Denied
0,EZYV01,14513,2007,592.2029,0,1,0,0,0,0,...,0,1,1,0,0,0,0,1,0,1
1,EZYV02,2412,2002,83425.6500,0,1,0,0,0,0,...,0,0,0,0,0,1,0,1,1,0
2,EZYV03,44444,2008,122996.8600,0,1,0,0,0,0,...,0,1,0,0,0,1,0,1,0,1
3,EZYV04,98,1897,83434.0300,0,1,0,0,0,0,...,0,1,0,0,0,1,0,1,0,1
4,EZYV05,1082,2005,149907.3900,1,0,0,0,0,0,...,1,0,0,0,0,1,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,2601,2008,77092.5700,0,1,0,0,0,0,...,1,0,0,0,0,1,0,1,1,0
25476,EZYV25477,3274,2006,279174.7900,0,1,0,0,0,0,...,0,0,0,0,0,1,0,1,1,0
25477,EZYV25478,1121,1910,146298.8500,0,1,0,0,0,0,...,1,0,0,0,0,1,1,0,1,0
25478,EZYV25479,1918,1887,86154.7700,0,1,0,0,0,0,...,0,1,0,0,0,1,0,1,1,0
25479,EZYV25480,3195,1960,70876.9100,0,1,0,0,0,0,...,0,0,0,0,0,1,0,1,1,0

**LableEncoder vs OneHotEncoder**

- Generally we dont want a relation between input columns

- we need both input columns are not correlated each other

- we need both input columns are **independent(X,Y)** each other

- we need both input columns are **perpendicular** each other

- we need both input columns are **Orthogonal** each other

- we need both input columns are **90 degrees phase shift** each other

- OneHotEncoder will achieve above

- But OneHotEncoder creates new columns

    - columns are incraese means dimenssions are incresae

    - More dimension data need more processing time

    - More dimension data need more infra

    - This is called **Curse of Dimensionality**