In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
visa_df=pd.read_csv(r"C:\Users\omkar\OneDrive\Documents\Gen_AI\Data_files\Visadataset.csv")

In [11]:
bank_df=pd.read_csv(r"C:\Users\omkar\OneDrive\Documents\Gen_AI\Data_files\bank.csv",
            sep=';')

In [ ]:
- shape

- size

- len

- columns

- dtypes

- isnull

- info

In [5]:
visa_df.dtypes

case_id                   object
continent                 object
education_of_employee     object
has_job_experience        object
requires_job_training     object
no_of_employees            int64
yr_of_estab                int64
region_of_employment      object
prevailing_wage          float64
unit_of_wage              object
full_time_position        object
case_status               object
dtype: object

In [7]:
type(visa_df)

pandas.core.frame.DataFrame

In [9]:
type(visa_df.dtypes)

pandas.core.series.Series

- series looks like dataframe 

- dataframe has column names matrix kind

- Series only index and its value 

- Series like a dictionary key and values

In [14]:
visa_df.dtypes.keys()

Index(['case_id', 'continent', 'education_of_employee', 'has_job_experience',
       'requires_job_training', 'no_of_employees', 'yr_of_estab',
       'region_of_employment', 'prevailing_wage', 'unit_of_wage',
       'full_time_position', 'case_status'],
      dtype='object')

In [16]:
visa_df.dtypes.values

array([dtype('O'), dtype('O'), dtype('O'), dtype('O'), dtype('O'),
       dtype('int64'), dtype('int64'), dtype('O'), dtype('float64'),
       dtype('O'), dtype('O'), dtype('O')], dtype=object)

In [20]:
list(visa_df.dtypes.items())

[('case_id', dtype('O')),
 ('continent', dtype('O')),
 ('education_of_employee', dtype('O')),
 ('has_job_experience', dtype('O')),
 ('requires_job_training', dtype('O')),
 ('no_of_employees', dtype('int64')),
 ('yr_of_estab', dtype('int64')),
 ('region_of_employment', dtype('O')),
 ('prevailing_wage', dtype('float64')),
 ('unit_of_wage', dtype('O')),
 ('full_time_position', dtype('O')),
 ('case_status', dtype('O'))]

**Make a Dataframe**

In [27]:
pd.DataFrame(visa_df.dtypes)

                             0
case_id                 object
continent               object
education_of_employee   object
has_job_experience      object
requires_job_training   object
no_of_employees          int64
yr_of_estab              int64
region_of_employment    object
prevailing_wage        float64
unit_of_wage            object
full_time_position      object
case_status             object

In [33]:
keys=visa_df.dtypes.keys()
values=visa_df.dtypes.values
pd.DataFrame(zip(keys,values),
            columns=['Column name','Data type'])

              Column name Data type
0                 case_id    object
1               continent    object
2   education_of_employee    object
3      has_job_experience    object
4   requires_job_training    object
5         no_of_employees     int64
6             yr_of_estab     int64
7    region_of_employment    object
8         prevailing_wage   float64
9            unit_of_wage    object
10     full_time_position    object
11            case_status    object

- When we have a dictionary

- First makes in to keys and values seperate

- Then create a dataframe

**task-1: seperate categorical columns and numerical**

In [41]:
dict1={'A':1,
      'B':2,
      'a':3,
      'b':4}
for i,j in dict1.items():
    #print(i,j)
    if i.isupper():
        print(j)

1
2

In [47]:
dict(visa_df.dtypes)
# iterate two i,j
# apply the condition
# if j=='object'
# append i in a list
# else
#  append i in list

{'case_id': dtype('O'),
 'continent': dtype('O'),
 'education_of_employee': dtype('O'),
 'has_job_experience': dtype('O'),
 'requires_job_training': dtype('O'),
 'no_of_employees': dtype('int64'),
 'yr_of_estab': dtype('int64'),
 'region_of_employment': dtype('O'),
 'prevailing_wage': dtype('float64'),
 'unit_of_wage': dtype('O'),
 'full_time_position': dtype('O'),
 'case_status': dtype('O')}

In [55]:
dtypes=dict(visa_df.dtypes)
cat,num=[],[]
for i,j in dtypes.items():
    if j=='object':
        cat.append(i)
    else:
        num.append(i)

In [61]:
dtypes=dict(visa_df.dtypes)
cat=[i for i,j in dtypes.items() if j=='object']
num=[i for i,j in dtypes.items() if j!='object']

**select_dtypes**

In [66]:
cat=visa_df.select_dtypes(include='object').columns

Index(['case_id', 'continent', 'education_of_employee', 'has_job_experience',
       'requires_job_training', 'region_of_employment', 'unit_of_wage',
       'full_time_position', 'case_status'],
      dtype='object')

In [68]:
num=visa_df.select_dtypes(exclude='object').columns

Index(['no_of_employees', 'yr_of_estab', 'prevailing_wage'], dtype='object')

In [ ]:
# import the packages
# read the data
# selectdtypes

**Data selection**

- take

- loc

- iloc

In [72]:
# select 100,200,300 rows data
rows=[100,200,300]
visa_df.take(rows,axis=0)

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
100,EZYV101,Asia,Master's,Y,N,2227,2007,Northeast,28243.79,Year,Y,Certified
200,EZYV201,Asia,Doctorate,Y,N,3282,1979,West,74441.11,Year,Y,Certified
300,EZYV301,Asia,Master's,Y,N,3268,2012,Midwest,101371.21,Year,Y,Certified

In [74]:
visa_df.columns

Index(['case_id', 'continent', 'education_of_employee', 'has_job_experience',
       'requires_job_training', 'no_of_employees', 'yr_of_estab',
       'region_of_employment', 'prevailing_wage', 'unit_of_wage',
       'full_time_position', 'case_status'],
      dtype='object')

In [80]:
cols=[1,5]
visa_df.take(cols,axis=1).take(rows,axis=0)

    continent  no_of_employees
100      Asia             2227
200      Asia             3282
300      Asia             3268

- Manual counting index of columns

- At a time i can not select rows and columns,we need to do two takes

**iloc**

iloc[rows,columns]

iloc[start:stop:step,start:stop:step]

In [87]:
visa_df.iloc[1:5,2:5]

  education_of_employee has_job_experience requires_job_training
1              Master's                  Y                     N
2            Bachelor's                  N                     Y
3            Bachelor's                  N                     N
4              Master's                  Y                     N

In [ ]:
visa_df.iloc[1:5,5] # w
visa_df.iloc[4,2:5] # w
visa_df.iloc[1:5,[2,6,7]] # w
visa_df.iloc[[100,200,300],2:5] # w
visa_df.iloc[[100,200,300],[2,6,7]] # w
visa_df.iloc[100,5] # w
visa_df.iloc[100] # w
visa_df.iloc[:,5] # w
visa_df.iloc[5,:] # w

In [89]:
# selecting a particular column
visa_df.iloc[:,5]

0        14513
1         2412
2        44444
3           98
4         1082
         ...
25475     2601
25476     3274
25477     1121
25478     1918
25479     3195
Name: no_of_employees, Length: 25480, dtype: int64

In [93]:
#visa_df.iloc[[:,5]]
visa_df.iloc[:,[5]]

       no_of_employees
0                14513
1                 2412
2                44444
3                   98
4                 1082
...                ...
25475             2601
25476             3274
25477             1121
25478             1918
25479             3195

[25480 rows x 1 columns]

In [ ]:
visa_df.iloc[:,5]  # series
visa_df.iloc[:,[5]] # df

In [95]:
visa_df.iloc[:,'no_of_employees']

ValueError: Location based indexing can only have [integer, integer slice (START point is INCLUDED, END point is EXCLUDED), listlike of integers, boolean array] types

- take

    - Manual counting

    - At a time we can not select rows and columns

- iloc

    - Manual counting

- loc

In [98]:
visa_df.loc[:,'no_of_employees']

0        14513
1         2412
2        44444
3           98
4         1082
         ...
25475     2601
25476     3274
25477     1121
25478     1918
25479     3195
Name: no_of_employees, Length: 25480, dtype: int64

In [ ]:
visa_df.loc[1:5,<>] 
visa_df.loc[4,2:<>] 
visa_df.loc[1:5,[<>]] 
visa_df.loc[[100,200,300],:] 
visa_df.loc[[100,200,300],[<>]] 
visa_df.loc[100,<>] 
visa_df.loc[100] 
visa_df.loc[:,<>] 
visa_df.loc[5,:]